name: netbird-connect

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  Connection_test:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Netbird Action
        uses: ./
        with:
          setup-key: ${{ secrets.GH_RUNNERS_NETBIRD_SETUP_KEY }}

      - name: Check for connection status
        run:
          netbird status

      - name: Test NetBird protected url connection
        run: |
          curl -i --connect-timeout 5 --max-time 10 --retry 3 --retry-delay 5 --retry-max-time 30 ${{ vars.TEST_URL }}
