name: netbird-connect

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  Connection_test:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Netbird Action
        uses: ./
        with:
          setup-key: ${{ secrets.NETBIRD_SETUP_KEY }}

      - name: Check for connection status
        run:
          netbird status
