name: Automatic Versioning and releasing
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
jobs:
  release:
    uses: Lupise/reusable-workflow--release-it/.github/workflows/versioning.yml@v2
    secrets: inherit